setwd("/Users/adaniel/Documents/personal/2014/Coursera/eda_proj1/")
data1 <- read.table(file="/Users/adaniel/Documents/personal/2014/Coursera/eda_proj1/household_power_consumption.txt", sep=";", header=TRUE)
data2 <- subset(data1, (data1[,1]=="2/2/2007" | data1[,1]=="1/2/2007"))
data2$Date <- strptime(paste(data2$Date,data2$Time), "%d/%m/%Y %H:%M:%S")
data2[,3] <- as.numeric(data2[,3])
data2[,4] <- as.numeric(data2[,4])
data2[,5] <- as.numeric(data2[,5])
data2[,7] <- as.numeric(data2[,7])
data2[,8] <- as.numeric(data2[,8])
data2[,9] <- as.numeric(data2[,9])
png(file = "plot4.png", width = 480 , height = 480)
par(mfrow = c(2,2))
with( data2, { plot(data2$Date, data2[,3], type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
               plot(data2$Date, data2[,5], type = "l", ylab = "Voltage", xlab = "datetime")
               plot(data2$Date, data2[,7], type = "l", col = "black", ylab = "Energy sub metering", xlab = "")
               lines(data2$Date, data2[,8], type = "l", col = "red")
               lines(data2$Date, data2[,9], type = "l", col= "blue")
               legend("topright", lty = "solid" , col = c("black", "red", "blue"), legend = c("sub_metering 1" , "sub-metering 2", "sub_metering 3" ))
               plot(data2$Date, data2[,4], type = "l", ylab = "Global Re-active Power (kilowatts)", xlab = "datetime")
                })
# title (main = " Global Active Power " , xlab = "Global Active Power (kilowatts)" )
dev.off()
# graphics.off()